/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package consumer;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class AppTest {

    @Test
    void appHasAGreeting() {
        ConsumerApp classUnderTest = new ConsumerApp();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
