/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package consumer;

public class ConsumerApp {

    public String getGreeting() {
        return "Hello Consumer!";
    }

    public static void main(String[] args) {
        System.out.println(new ConsumerApp().getGreeting());

    }

}
